// types/history.ts

export type TradeDirection = "LONG" | "SHORT";
export type TradeOutcome =
  | "FULL SUCCESS"
  | "PARTIAL SUCCESS"
  | "MISTAKE"
  | "BREAK EVEN";
export type SortOption = "Newest" | "Oldest" | "Highest PnL" | "Lowest PnL";
export type MarketFilter = "All" | "Crypto" | "Indian" | "Forex";
export type DirectionFilter = "Both" | "Long" | "Short";
export type OutcomeFilter =
  | "All Outcomes"
  | "Full Success"
  | "Partial Success"
  | "Mistake"
  | "Followed Plan";

export interface HistoryTrade {
  id: string;
  date: string; // "24 OCT 2023"
  time: string; // "09:45 AM"
  symbol: string; // "BTC/USDT"
  direction: TradeDirection;
  pnl: number; // signed dollar value
  pnlPercent: number; // signed percentage
  entryPrice: number;
  exitPrice: number;
  quantity: number;
  strategy: string;
  rrRatio: string; // "1:3.2"
  outcome: TradeOutcome;
  market: MarketFilter;
  charges?: number;
  margin?: number;
}

export const SORT_OPTIONS: SortOption[] = [
  "Newest",
  "Oldest",
  "Highest PnL",
  "Lowest PnL",
];

export const MARKET_OPTIONS: MarketFilter[] = [
  "All",
  "Crypto",
  "Indian",
  "Forex",
];

export const DIRECTION_OPTIONS: DirectionFilter[] = ["Both", "Long", "Short"];

export const OUTCOME_OPTIONS: OutcomeFilter[] = [
  "All Outcomes",
  "Full Success",
  "Partial Success",
  "Mistake",
  "Followed Plan",
];

export const OUTCOME_COLORS: Record<
  TradeOutcome,
  { text: string; bg: string; border: string }
> = {
  "FULL SUCCESS": {
    text: "#43e5b1",
    bg: "rgba(67,229,177,0.12)",
    border: "#43e5b1",
  },
  "PARTIAL SUCCESS": {
    text: "#f9c449",
    bg: "rgba(249,196,73,0.12)",
    border: "#f9c449",
  },
  MISTAKE: { text: "#ff5451", bg: "rgba(255,84,81,0.12)", border: "#ff5451" },
  "BREAK EVEN": {
    text: "#adc6ff",
    bg: "rgba(173,198,255,0.12)",
    border: "#adc6ff",
  },
};

// ── 40 mock trades ─────────────────────────────────────────────────────────────
export const MOCK_HISTORY: HistoryTrade[] = [
  {
    id: "1",
    date: "24 OCT 2023",
    time: "09:45 AM",
    symbol: "BTC/USDT",
    direction: "LONG",
    pnl: 1450.0,
    pnlPercent: 4.12,
    entryPrice: 34250.2,
    exitPrice: 35660.45,
    quantity: 1,
    strategy: "VWAP Breakout",
    rrRatio: "1:3.2",
    outcome: "FULL SUCCESS",
    market: "Crypto",
  },
  {
    id: "2",
    date: "23 OCT 2023",
    time: "02:15 PM",
    symbol: "ETH/USDT",
    direction: "SHORT",
    pnl: -220.0,
    pnlPercent: -1.15,
    entryPrice: 1842.5,
    exitPrice: 1863.7,
    quantity: 1,
    strategy: "Mean Reversion",
    rrRatio: "1:1.8",
    outcome: "MISTAKE",
    market: "Crypto",
  },
  {
    id: "3",
    date: "23 OCT 2023",
    time: "11:30 AM",
    symbol: "SOL/USDT",
    direction: "LONG",
    pnl: 84.5,
    pnlPercent: 0.62,
    entryPrice: 31.25,
    exitPrice: 31.45,
    quantity: 1,
    strategy: "Inside Bar",
    rrRatio: "1:1.0",
    outcome: "PARTIAL SUCCESS",
    market: "Crypto",
  },
  {
    id: "4",
    date: "22 OCT 2023",
    time: "10:00 AM",
    symbol: "NIFTY 50",
    direction: "LONG",
    pnl: 3200.0,
    pnlPercent: 2.4,
    entryPrice: 19500,
    exitPrice: 19968,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:2.5",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "5",
    date: "22 OCT 2023",
    time: "03:20 PM",
    symbol: "BANKNIFTY",
    direction: "SHORT",
    pnl: -850.0,
    pnlPercent: -1.8,
    entryPrice: 44200,
    exitPrice: 44995,
    quantity: 1,
    strategy: "VWAP Reversion",
    rrRatio: "1:1.2",
    outcome: "MISTAKE",
    market: "Indian",
  },
  {
    id: "6",
    date: "21 OCT 2023",
    time: "09:15 AM",
    symbol: "AAPL",
    direction: "LONG",
    pnl: 320.0,
    pnlPercent: 1.85,
    entryPrice: 172.4,
    exitPrice: 175.6,
    quantity: 1,
    strategy: "Trend Follow",
    rrRatio: "1:2.0",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "7",
    date: "21 OCT 2023",
    time: "01:45 PM",
    symbol: "TSLA",
    direction: "SHORT",
    pnl: -180.0,
    pnlPercent: -0.75,
    entryPrice: 215.3,
    exitPrice: 216.9,
    quantity: 1,
    strategy: "Mean Reversion",
    rrRatio: "1:1.5",
    outcome: "MISTAKE",
    market: "Indian",
  },
  {
    id: "8",
    date: "20 OCT 2023",
    time: "10:30 AM",
    symbol: "EUR/USD",
    direction: "LONG",
    pnl: 560.0,
    pnlPercent: 3.2,
    entryPrice: 1.058,
    exitPrice: 1.0614,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:3.0",
    outcome: "FULL SUCCESS",
    market: "Forex",
  },
  {
    id: "9",
    date: "20 OCT 2023",
    time: "04:00 PM",
    symbol: "GBP/USD",
    direction: "SHORT",
    pnl: -90.0,
    pnlPercent: -0.45,
    entryPrice: 1.213,
    exitPrice: 1.2152,
    quantity: 1,
    strategy: "Inside Bar",
    rrRatio: "1:1.0",
    outcome: "BREAK EVEN",
    market: "Forex",
  },
  {
    id: "10",
    date: "19 OCT 2023",
    time: "09:45 AM",
    symbol: "XRP/USDT",
    direction: "LONG",
    pnl: 210.0,
    pnlPercent: 1.5,
    entryPrice: 0.542,
    exitPrice: 0.5501,
    quantity: 1,
    strategy: "VWAP Breakout",
    rrRatio: "1:2.2",
    outcome: "PARTIAL SUCCESS",
    market: "Crypto",
  },
  {
    id: "11",
    date: "18 OCT 2023",
    time: "11:00 AM",
    symbol: "RELIANCE",
    direction: "LONG",
    pnl: 4500.0,
    pnlPercent: 3.1,
    entryPrice: 2410,
    exitPrice: 2484.6,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:3.5",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "12",
    date: "18 OCT 2023",
    time: "02:30 PM",
    symbol: "INFY",
    direction: "SHORT",
    pnl: -320.0,
    pnlPercent: -1.2,
    entryPrice: 1450,
    exitPrice: 1467.4,
    quantity: 1,
    strategy: "Mean Reversion",
    rrRatio: "1:1.3",
    outcome: "MISTAKE",
    market: "Indian",
  },
  {
    id: "13",
    date: "17 OCT 2023",
    time: "10:15 AM",
    symbol: "BNB/USDT",
    direction: "LONG",
    pnl: 380.0,
    pnlPercent: 2.0,
    entryPrice: 215.4,
    exitPrice: 219.7,
    quantity: 1,
    strategy: "Trend Follow",
    rrRatio: "1:2.0",
    outcome: "FULL SUCCESS",
    market: "Crypto",
  },
  {
    id: "14",
    date: "17 OCT 2023",
    time: "03:45 PM",
    symbol: "MSFT",
    direction: "LONG",
    pnl: 640.0,
    pnlPercent: 2.1,
    entryPrice: 330.2,
    exitPrice: 337.1,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:2.5",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "15",
    date: "16 OCT 2023",
    time: "09:30 AM",
    symbol: "USD/JPY",
    direction: "SHORT",
    pnl: -145.0,
    pnlPercent: -0.95,
    entryPrice: 149.6,
    exitPrice: 149.74,
    quantity: 1,
    strategy: "VWAP Reversion",
    rrRatio: "1:1.0",
    outcome: "BREAK EVEN",
    market: "Forex",
  },
  {
    id: "16",
    date: "16 OCT 2023",
    time: "01:00 PM",
    symbol: "DOGE/USDT",
    direction: "LONG",
    pnl: 125.0,
    pnlPercent: 1.2,
    entryPrice: 0.0618,
    exitPrice: 0.0625,
    quantity: 1,
    strategy: "Momentum",
    rrRatio: "1:1.5",
    outcome: "PARTIAL SUCCESS",
    market: "Crypto",
  },
  {
    id: "17",
    date: "15 OCT 2023",
    time: "10:45 AM",
    symbol: "HDFCBANK",
    direction: "LONG",
    pnl: 2800.0,
    pnlPercent: 1.9,
    entryPrice: 1620,
    exitPrice: 1650.8,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:2.0",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "18",
    date: "15 OCT 2023",
    time: "02:00 PM",
    symbol: "GOOGL",
    direction: "SHORT",
    pnl: -260.0,
    pnlPercent: -0.8,
    entryPrice: 136.8,
    exitPrice: 137.9,
    quantity: 1,
    strategy: "Mean Reversion",
    rrRatio: "1:1.2",
    outcome: "MISTAKE",
    market: "Indian",
  },
  {
    id: "19",
    date: "14 OCT 2023",
    time: "11:15 AM",
    symbol: "ADA/USDT",
    direction: "LONG",
    pnl: 95.0,
    pnlPercent: 0.85,
    entryPrice: 0.253,
    exitPrice: 0.2552,
    quantity: 1,
    strategy: "Inside Bar",
    rrRatio: "1:1.0",
    outcome: "PARTIAL SUCCESS",
    market: "Crypto",
  },
  {
    id: "20",
    date: "13 OCT 2023",
    time: "09:00 AM",
    symbol: "EUR/GBP",
    direction: "LONG",
    pnl: 340.0,
    pnlPercent: 1.6,
    entryPrice: 0.861,
    exitPrice: 0.8638,
    quantity: 1,
    strategy: "Trend Follow",
    rrRatio: "1:2.0",
    outcome: "FULL SUCCESS",
    market: "Forex",
  },
  {
    id: "21",
    date: "12 OCT 2023",
    time: "10:00 AM",
    symbol: "TCS",
    direction: "LONG",
    pnl: 5200.0,
    pnlPercent: 2.8,
    entryPrice: 3680,
    exitPrice: 3783,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:3.0",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "22",
    date: "12 OCT 2023",
    time: "03:00 PM",
    symbol: "AVAX/USDT",
    direction: "SHORT",
    pnl: -310.0,
    pnlPercent: -2.1,
    entryPrice: 10.4,
    exitPrice: 10.62,
    quantity: 1,
    strategy: "VWAP Reversion",
    rrRatio: "1:1.1",
    outcome: "MISTAKE",
    market: "Crypto",
  },
  {
    id: "23",
    date: "11 OCT 2023",
    time: "11:45 AM",
    symbol: "AMZN",
    direction: "LONG",
    pnl: 720.0,
    pnlPercent: 2.5,
    entryPrice: 127.4,
    exitPrice: 130.6,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:2.8",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "24",
    date: "10 OCT 2023",
    time: "02:15 PM",
    symbol: "LINK/USDT",
    direction: "LONG",
    pnl: 175.0,
    pnlPercent: 1.3,
    entryPrice: 7.24,
    exitPrice: 7.334,
    quantity: 1,
    strategy: "Momentum",
    rrRatio: "1:1.8",
    outcome: "PARTIAL SUCCESS",
    market: "Crypto",
  },
  {
    id: "25",
    date: "09 OCT 2023",
    time: "09:30 AM",
    symbol: "USD/CAD",
    direction: "SHORT",
    pnl: -75.0,
    pnlPercent: -0.4,
    entryPrice: 1.364,
    exitPrice: 1.3648,
    quantity: 1,
    strategy: "Inside Bar",
    rrRatio: "1:1.0",
    outcome: "BREAK EVEN",
    market: "Forex",
  },
  {
    id: "26",
    date: "08 OCT 2023",
    time: "10:30 AM",
    symbol: "WIPRO",
    direction: "LONG",
    pnl: 1800.0,
    pnlPercent: 2.4,
    entryPrice: 415,
    exitPrice: 424.96,
    quantity: 1,
    strategy: "VWAP Breakout",
    rrRatio: "1:2.2",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "27",
    date: "07 OCT 2023",
    time: "01:30 PM",
    symbol: "MATIC/USDT",
    direction: "LONG",
    pnl: 240.0,
    pnlPercent: 1.75,
    entryPrice: 0.528,
    exitPrice: 0.5372,
    quantity: 1,
    strategy: "Trend Follow",
    rrRatio: "1:2.0",
    outcome: "FULL SUCCESS",
    market: "Crypto",
  },
  {
    id: "28",
    date: "06 OCT 2023",
    time: "03:15 PM",
    symbol: "META",
    direction: "SHORT",
    pnl: -190.0,
    pnlPercent: -0.6,
    entryPrice: 305.4,
    exitPrice: 307.22,
    quantity: 1,
    strategy: "Mean Reversion",
    rrRatio: "1:1.0",
    outcome: "MISTAKE",
    market: "Indian",
  },
  {
    id: "29",
    date: "05 OCT 2023",
    time: "11:00 AM",
    symbol: "AUD/USD",
    direction: "LONG",
    pnl: 410.0,
    pnlPercent: 2.8,
    entryPrice: 0.632,
    exitPrice: 0.6338,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:3.0",
    outcome: "FULL SUCCESS",
    market: "Forex",
  },
  {
    id: "30",
    date: "04 OCT 2023",
    time: "09:45 AM",
    symbol: "BTC/USDT",
    direction: "LONG",
    pnl: 2100.0,
    pnlPercent: 6.2,
    entryPrice: 27500,
    exitPrice: 29205,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:4.0",
    outcome: "FULL SUCCESS",
    market: "Crypto",
  },
  {
    id: "31",
    date: "03 OCT 2023",
    time: "02:00 PM",
    symbol: "AXISBANK",
    direction: "SHORT",
    pnl: -560.0,
    pnlPercent: -1.5,
    entryPrice: 1020,
    exitPrice: 1035.3,
    quantity: 1,
    strategy: "VWAP Reversion",
    rrRatio: "1:1.0",
    outcome: "MISTAKE",
    market: "Indian",
  },
  {
    id: "32",
    date: "02 OCT 2023",
    time: "10:15 AM",
    symbol: "NVDA",
    direction: "LONG",
    pnl: 1840.0,
    pnlPercent: 4.1,
    entryPrice: 434.2,
    exitPrice: 452.0,
    quantity: 1,
    strategy: "Momentum",
    rrRatio: "1:3.5",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "33",
    date: "01 OCT 2023",
    time: "11:30 AM",
    symbol: "DOT/USDT",
    direction: "LONG",
    pnl: 130.0,
    pnlPercent: 1.05,
    entryPrice: 4.01,
    exitPrice: 4.052,
    quantity: 1,
    strategy: "Inside Bar",
    rrRatio: "1:1.5",
    outcome: "PARTIAL SUCCESS",
    market: "Crypto",
  },
  {
    id: "34",
    date: "30 SEP 2023",
    time: "09:30 AM",
    symbol: "NZD/USD",
    direction: "SHORT",
    pnl: -50.0,
    pnlPercent: -0.3,
    entryPrice: 0.595,
    exitPrice: 0.5953,
    quantity: 1,
    strategy: "Inside Bar",
    rrRatio: "1:1.0",
    outcome: "BREAK EVEN",
    market: "Forex",
  },
  {
    id: "35",
    date: "29 SEP 2023",
    time: "01:00 PM",
    symbol: "ETH/USDT",
    direction: "LONG",
    pnl: 960.0,
    pnlPercent: 2.9,
    entryPrice: 1620.0,
    exitPrice: 1667.0,
    quantity: 1,
    strategy: "VWAP Breakout",
    rrRatio: "1:2.8",
    outcome: "FULL SUCCESS",
    market: "Crypto",
  },
  {
    id: "36",
    date: "28 SEP 2023",
    time: "10:45 AM",
    symbol: "MARUTI",
    direction: "LONG",
    pnl: 6200.0,
    pnlPercent: 3.5,
    entryPrice: 10400,
    exitPrice: 10764,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:3.2",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
  {
    id: "37",
    date: "27 SEP 2023",
    time: "03:00 PM",
    symbol: "NFLX",
    direction: "SHORT",
    pnl: -220.0,
    pnlPercent: -0.55,
    entryPrice: 395.4,
    exitPrice: 397.57,
    quantity: 1,
    strategy: "Mean Reversion",
    rrRatio: "1:1.0",
    outcome: "MISTAKE",
    market: "Indian",
  },
  {
    id: "38",
    date: "26 SEP 2023",
    time: "09:15 AM",
    symbol: "LTC/USDT",
    direction: "LONG",
    pnl: 310.0,
    pnlPercent: 2.2,
    entryPrice: 62.4,
    exitPrice: 63.77,
    quantity: 1,
    strategy: "Trend Follow",
    rrRatio: "1:2.5",
    outcome: "FULL SUCCESS",
    market: "Crypto",
  },
  {
    id: "39",
    date: "25 SEP 2023",
    time: "11:30 AM",
    symbol: "CHF/USD",
    direction: "LONG",
    pnl: 280.0,
    pnlPercent: 1.7,
    entryPrice: 1.084,
    exitPrice: 1.0958,
    quantity: 1,
    strategy: "Breakout",
    rrRatio: "1:2.0",
    outcome: "PARTIAL SUCCESS",
    market: "Forex",
  },
  {
    id: "40",
    date: "24 SEP 2023",
    time: "02:30 PM",
    symbol: "ICICI",
    direction: "LONG",
    pnl: 3400.0,
    pnlPercent: 2.6,
    entryPrice: 940,
    exitPrice: 964.44,
    quantity: 1,
    strategy: "VWAP Breakout",
    rrRatio: "1:2.8",
    outcome: "FULL SUCCESS",
    market: "Indian",
  },
];
